name = "BIGUQ"
uuid = "7f9c7709-75fb-5397-acba-f980073965f6"
version = "0.8.0"

[deps]
AffineInvariantMCMC = "a0f608ac-68d0-5108-ad9a-0cdca73324f3"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
RobustPmap = "27aeedcb-f738-516b-a0b8-3211cf1146e5"

[compat]
AffineInvariantMCMC = "^0"
BlackBoxOptim = "^0"
DataFrames = "^0"
Distributions = "^0"
ForwardDiff = "^0"
RobustPmap = "^0"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
